[package]
name = "my_first_email"
version = "0.1.0"
authors = ["spenc"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = "0.9"
lettre_email = "0.9"
imap = "2"
native-tls = "0.2"
anyhow = "1.0"